# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Content')),
            ],
        ),
    ]
