# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170417_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='attachment',
            field=models.FileField(default='', upload_to='attachments'),
            preserve_default=False,
        ),
    ]
