# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170523_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
